/* plugs.js - the plug and socket types, for the plugs page.
   Pictures from Wikimedia Commons, credited under each image. */
window.MUSEUM_PLUGS = [
  {"letter":"A","name":"NEMA 1-15","where":"North America, Japan","desc":"Two flat blades, no earth. The oldest type still in everyday use.","file":"plugs/a.jpg","source":"https://commons.wikimedia.org/wiki/File:Europlug_compared_to_polarized_NEMA_1-15_plug.jpg","license":"CC BY-SA 4.0","credit":"FF-UK"},
  {"letter":"B","name":"NEMA 5-15","where":"North America, Japan","desc":"Type A with a round earth pin added below the blades.","file":"plugs/b.jpg","source":"https://commons.wikimedia.org/wiki/File:B_plug.jpg","license":"Public domain","credit":"Conrad H. McGregor"},
  {"letter":"C","name":"CEE 7/16 Europlug","where":"Europe, most of the world","desc":"Two round pins, 4.8 mm, unearthed. Fits almost any Continental socket.","file":"plugs/c.jpg","source":"https://commons.wikimedia.org/wiki/File:Euro-Flachstecker_2.jpg","license":"Public domain","credit":"SomnusDe"},
  {"letter":"D","name":"BS 546, 5 A","where":"India, Sri Lanka, Nepal","desc":"Three round pins in a triangle, the earth pin much larger.","file":"plugs/d.jpg","source":"https://commons.wikimedia.org/wiki/File:BS-546-3-pin-plugs.jpg","license":"Public domain","credit":"Ziltro at English Wikipedia"},
  {"letter":"E","name":"CEE 7/5","where":"France, Belgium, Poland","desc":"Round pins with an earth pin projecting from the socket.","file":"plugs/e.jpg","source":"https://commons.wikimedia.org/wiki/File:European_cee7-7_plug_cee7-5_socket_type_E.jpg","license":"CC BY-SA 4.0","credit":"Electro-world-standard"},
  {"letter":"F","name":"CEE 7/4 Schuko","where":"Germany, most of Europe","desc":"Side earthing clips instead of a pin. Fits C and E plugs.","file":"plugs/f.jpg","source":"https://commons.wikimedia.org/wiki/File:Cee7-7_plug_%28french-schuko%29.jpg","license":"CC BY-SA 4.0","credit":"Electro-world-standard"},
  {"letter":"G","name":"BS 1363","where":"United Kingdom, Ireland, Malta","desc":"Three rectangular pins, a fuse inside the plug, shutters in the socket.","file":"plugs/g.jpg","source":"https://commons.wikimedia.org/wiki/File:AC_Power_Plug_BS_1363.jpg","license":"CC BY-SA 2.0 de","credit":"User:C.Löser (de:Benutzer:C.Löser)"},
  {"letter":"H","name":"SI 32","where":"Israel, Gaza, West Bank","desc":"Three flat pins in a Y shape, unique to Israel.","file":"plugs/h.jpg","source":"https://commons.wikimedia.org/wiki/File:Israeli-type-H-plugs-and-socket.jpg","license":"Public domain","credit":"fr:Utilisateur:Kiddo"},
  {"letter":"I","name":"AS/NZS 3112","where":"Australia, New Zealand, China, Argentina","desc":"Two angled flat pins with a vertical earth pin.","file":"plugs/i.jpg","source":"https://commons.wikimedia.org/wiki/File:Aust_AC_plug.jpg","license":"Public domain","credit":"Jim Donovan"},
  {"letter":"J","name":"SEV 1011","where":"Switzerland, Liechtenstein","desc":"Three round pins set close together, offset from centre.","file":"plugs/j.jpg","source":"https://commons.wikimedia.org/wiki/File:AC_Power_Plug_Type_J.jpg","license":"CC BY-SA 2.0 de","credit":"C.Löser (C.Löser)"},
  {"letter":"K","name":"DS 60884-2-D1","where":"Denmark, Greenland","desc":"Like a Schuko but the earth pin is a pin, not a clip.","file":"plugs/k.jpg","source":"https://commons.wikimedia.org/wiki/File:Danish_type_K_plug.jpg","license":"CC BY-SA 4.0","credit":"Original:  Chameleon"},
  {"letter":"L","name":"CEI 23-50","where":"Italy, Chile, Uruguay","desc":"Three round pins in a straight line, two sizes of spacing.","file":"plugs/l.jpg","source":"https://commons.wikimedia.org/wiki/File:Ita_plug_16A_10A.jpg","license":"CC BY-SA 3.0","credit":"Marco Gilardetti"},
  {"letter":"M","name":"BS 546, 15 A","where":"South Africa, India, Malaysia","desc":"The large version of type D, rated for 15 amperes.","file":"plugs/m.jpg","source":"https://commons.wikimedia.org/wiki/File:SANS_164-1_%26_164-2_sockets.jpg","license":"CC BY-SA 4.0","credit":"FF-UK"},
  {"letter":"N","name":"IEC 60906-1 / NBR 14136","where":"Brazil, South Africa","desc":"Three round pins with the earth pin slightly offset.","file":"plugs/n.jpg","source":"https://commons.wikimedia.org/wiki/File:NBR-14136_-_40_A%2C_250_V.jpg","license":"CC0","credit":"Cosmic Console"},
  {"letter":"O","name":"TIS 166-2549","where":"Thailand","desc":"A hybrid of A and C pins in one round body.","file":"plugs/o.jpg","source":"https://commons.wikimedia.org/wiki/File:Thai_TIS_166-2549_mains_plug.jpg","license":"CC BY-SA 3.0","credit":"Paul_012"}
];