/* relics.js — the objects on the photos & video page.
   Every image is stored locally in gallery/ and credited back to Wikimedia
   Commons under the licence named here. `copy` marks a replica, a cast or a
   reproduction, which is stated on the page rather than passed off as the
   original object.
   Change a line here, then run: node build.js */
window.MUSEUM_RELICS = [
  { name: "Benin Bronze Plaque", museum: "British Museum", place: "London", period: "16th c.", site: "https://www.britishmuseum.org", file: "gallery/benin-bronze-plaque.jpg", source: "https://commons.wikimedia.org/wiki/File%3ACast_Brass_Plaque_%2CCurrently_at_the_British_Museum.jpg", license: "CC BY-SA 4.0", credit: "SpeakingArch", note: "Cast for the palace of Benin City and taken in 1897; where they belong is still being decided." },
  { name: "Rosetta Stone", museum: "British Museum", place: "London", period: "196 BC", site: "https://www.britishmuseum.org", file: "gallery/rosetta-stone.jpg", source: "https://commons.wikimedia.org/wiki/File%3ARosetta_Stone.JPG", license: "CC BY-SA 4.0", credit: "Hans Hillewaert", note: "One decree in three scripts, which is what made Egyptian writing readable again." },
  { name: "Terracotta Army", museum: "Mausoleum of Qin Shi Huang", place: "Xi'an", period: "c. 210 BC", site: "https://www.bmy.com.cn", file: "gallery/terracotta-army.jpg", source: "https://commons.wikimedia.org/wiki/File%3ATerracotta_warriors_%2881726%29.jpg", license: "CC BY-SA 4.0", credit: "Ideophagous", note: "Thousands of figures, no two quite alike, standing guard over a tomb nobody has opened." },
  { name: "Jade Burial Suit", museum: "Hebei Museum", place: "Shijiazhuang", period: "2nd c. BC", site: "http://www.hebeimuseum.org.cn", file: "gallery/jade-burial-suit.jpg", source: "https://commons.wikimedia.org/wiki/File%3AWestern_Han_Jade_Burial_Suit_of_Liu_Sheng_-_a.jpg", license: "CC0", credit: "Gary Todd", note: "Over two thousand jade plates sewn together with gold thread, an expensive bet on not decaying." },
  { name: "Bronze Mask", museum: "Sanxingdui Museum", place: "Guanghan", period: "c. 1200 BC", site: "https://www.sxd.cn", file: "gallery/bronze-mask.jpg", source: "https://commons.wikimedia.org/wiki/File%3ABronze_Animal_Mask_from_Sanxingdui_8.jpg", license: "CC0", credit: "Gary Todd", note: "Casting from a culture unknown until 1986 that still matches nothing else made in China." },
  { name: "Tutankhamun Mask", museum: "Egyptian Museum", place: "Cairo", period: "c. 1323 BC", site: "https://egymonuments.gov.eg/en/", file: "gallery/tutankhamun-mask.jpg", source: "https://commons.wikimedia.org/wiki/File%3AMask_of_Tutankhamun_in_2025.jpg", license: "CC BY 4.0", credit: "Dawid Wdowczyk", note: "Eleven kilos of gold, found in 1922 still strapped to the mummy it was made for." },
  { name: "Mona Lisa", museum: "Louvre", place: "Paris", period: "1503-1519", site: "https://www.louvre.fr/en", file: "gallery/mona-lisa.jpg", source: "https://commons.wikimedia.org/wiki/File%3AMona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg", license: "Public domain", credit: "Leonardo da Vinci", note: "Small, dark, and behind glass ever since a visitor walked out with it in 1911." },
  { name: "Venus de Milo", museum: "Louvre", place: "Paris", period: "c. 130 BC", site: "https://www.louvre.fr/en", file: "gallery/venus-de-milo.jpg", source: "https://commons.wikimedia.org/wiki/File%3AVenus_de_Milo.JPG", license: "CC BY-SA 2.5", credit: "Unknown author", note: "Found on Melos in 1820 without her arms, which nobody has convincingly put back." },
  { name: "Winged Victory of Samothrace", museum: "Louvre", place: "Paris", period: "c. 190 BC", site: "https://www.louvre.fr/en", file: "gallery/winged-victory-of-samothrace.jpg", source: "https://commons.wikimedia.org/wiki/File%3ANike_of_Samothrace%2C_Paris%2C_Louvre.jpg", license: "CC0", credit: "Wilfredor", note: "Headless and armless, and still the loudest object in the staircase it stands in." },
  { name: "Bust of Nefertiti", museum: "Neues Museum", place: "Berlin", period: "c. 1345 BC", site: "https://www.neues-museum.de/en/", file: "gallery/bust-of-nefertiti.jpg", source: "https://commons.wikimedia.org/wiki/File%3ANofretete_Neues_Museum.jpg", license: "CC BY-SA 3.0", credit: "Philip Pikart", note: "Painted plaster over a limestone core, and probably a workshop model rather than a portrait." },
  { name: "Narmer Palette", museum: "Egyptian Museum", place: "Cairo", period: "c. 3100 BC", site: "https://egymonuments.gov.eg/en/", file: "gallery/narmer-palette.jpg", source: "https://commons.wikimedia.org/wiki/File%3ANarmer_Palette_%28verso%29.jpg", license: "CC BY-SA 4.0", credit: "Heagy1", note: "Among the earliest objects to show one ruler over both halves of Egypt." },
  { name: "Elgin Marbles", museum: "British Museum", place: "London", period: "c. 440 BC", site: "https://www.britishmuseum.org", file: "gallery/elgin-marbles.jpg", source: "https://commons.wikimedia.org/wiki/File%3AThe_Parthenon_sculptures%2C_British_Museum_%2814063376069%29.jpg", license: "CC BY-SA 2.0", credit: "Carole Raddato", note: "Cut off the Parthenon in the 1800s and argued over in every room they have occupied since." },
  { name: "The Great Wave off Kanagawa", museum: "The Met", place: "New York", period: "c. 1831", site: "https://www.metmuseum.org", file: "gallery/the-great-wave-off-kanagawa.jpg", source: "https://commons.wikimedia.org/wiki/File%3ATsunami_by_hokusai_19th_century.jpg", license: "Public domain", credit: "Katsushika Hokusai", note: "A woodblock print, so the wave is flat ink and no two impressions are identical." },
  { name: "Sunflowers", museum: "National Gallery", place: "London", period: "1888", site: "https://www.nationalgallery.org.uk", file: "gallery/sunflowers.jpg", source: "https://commons.wikimedia.org/wiki/File%3AVincent_van_Gogh_-_Sunflowers_%281888%2C_National_Gallery_London%29.jpg", license: "Public domain", credit: "Vincent van Gogh", note: "One of several versions painted for Gauguin's room; this is the one kept in London." },
  { name: "Liberty Leading the People", museum: "Louvre", place: "Paris", period: "1830", site: "https://www.louvre.fr/en", file: "gallery/liberty-leading-the-people.jpg", source: "https://commons.wikimedia.org/wiki/File%3AEug%C3%A8ne_Delacroix_-_La_libert%C3%A9_guidant_le_peuple.jpg", license: "Public domain", credit: "Eugène Delacroix", note: "Painted months after three days of street fighting, with the allegory wading over the bodies." },
  { name: "The Night Watch", museum: "Rijksmuseum", place: "Amsterdam", period: "1642", site: "https://www.rijksmuseum.nl/en", file: "gallery/the-night-watch.jpg", source: "https://commons.wikimedia.org/wiki/File%3ALa_ronda_de_noche%2C_por_Rembrandt_van_Rijn.jpg", license: "Public domain", credit: "Rembrandt", note: "A group portrait that turned into a scene, and was trimmed on all sides to fit a wall." },
  { name: "Girl with a Pearl Earring", museum: "Mauritshuis", place: "The Hague", period: "c. 1665", site: "https://www.mauritshuis.nl/en", file: "gallery/girl-with-a-pearl-earring.jpg", source: "https://commons.wikimedia.org/wiki/File%3A1665_Girl_with_a_Pearl_Earring.jpg", license: "Public domain", credit: "Johannes Vermeer", note: "Not a portrait but a tronie: a study of a face, a turban and one wet highlight." },
  { name: "Mogao Cave Mural", museum: "Dunhuang Academy", place: "Dunhuang", period: "7th-9th c.", site: "https://www.e-dunhuang.com", file: "gallery/mogao-cave-mural.jpg", source: "https://commons.wikimedia.org/wiki/File%3AReproduced_Mural_of_220_cave%2C_Mogao_caves%2C_Dunhuang.jpg", license: "CC BY-SA 3.0", credit: "Hiroooooo", copy: true, note: "A reproduction: most of the caves are shut to visitors to keep the pigment on the wall." },
  { name: "Along the River During Qingming", museum: "Palace Museum", place: "Beijing", period: "12th c.", site: "https://www.dpm.org.cn", file: "gallery/along-the-river-during-qingming.jpg", source: "https://commons.wikimedia.org/wiki/File%3AAlong_the_River_During_the_Qingming_Festival_%28detail_of_original%29.jpg", license: "Public domain", credit: "Zhang Zeduan", note: "A detail of the original handscroll, which runs for several metres and holds hundreds of figures." },
  { name: "Houmuwu Ding", museum: "National Museum of China", place: "Beijing", period: "c. 1200 BC", site: "https://www.chnmuseum.cn", file: "gallery/houmuwu-ding.jpg", source: "https://commons.wikimedia.org/wiki/File%3AHouMuWuDingFullView.jpg", license: "CC BY-SA 3.0", credit: "Mlogic", note: "The largest bronze vessel to survive from the Shang dynasty, at 832 kg." },
  { name: "Code of Hammurabi", museum: "Louvre", place: "Paris", period: "c. 1754 BC", site: "https://www.louvre.fr/en", file: "gallery/code-of-hammurabi.jpg", source: "https://commons.wikimedia.org/wiki/File%3AP1050763_Louvre_code_Hammurabi_face_rwk.JPG", license: "CC BY 3.0", credit: "Mbzt", note: "282 rulings carved into a stone pillar, topped by the king being handed them." },
  { name: "Book of Kells", museum: "Trinity College", place: "Dublin", period: "c. 800", site: "https://www.tcd.ie/", file: "gallery/book-of-kells.jpg", source: "https://commons.wikimedia.org/wiki/File%3AKellsFol292rIncipJohn.jpg", license: "Public domain", credit: "Unknown author", note: "Four gospel books with more decoration than text on the page; a volume is turned daily." },
  { name: "Bayeux Tapestry", museum: "Bayeux Museum", place: "Bayeux", period: "11th c.", site: "https://bayeuxmuseum.com/en/", file: "gallery/bayeux-tapestry.jpg", source: "https://commons.wikimedia.org/wiki/File%3ABayeux_Tapestry_scene57_Harold_death.jpg", license: "Public domain", credit: "Myrabella", note: "Seventy metres of embroidered linen setting out the Norman case for 1066." },
  { name: "Sutton Hoo Helmet", museum: "British Museum", place: "London", period: "c. 625", site: "https://www.britishmuseum.org", file: "gallery/sutton-hoo-helmet.jpg", source: "https://commons.wikimedia.org/wiki/File%3ASutton_Hoo_helmet_2016.png", license: "Public domain", credit: "Geni", note: "An Anglo-Saxon helmet from a ship burial, reassembled from corroded fragments." },
  { name: "Lewis Chessmen", museum: "British Museum", place: "London", period: "12th c.", site: "https://www.britishmuseum.org", file: "gallery/lewis-chessmen.jpg", source: "https://commons.wikimedia.org/wiki/File%3AThe_Warder%2C_Lewis_Chessmen%2C_British_Museum.jpg", license: "CC BY 2.0", credit: "Rob Roy", note: "Chess pieces carved from walrus ivory, found buried in a Hebridean sandbank in 1831." },
  { name: "Sun Stone", museum: "National Museum of Anthropology", place: "Mexico City", period: "c. 1479", site: "https://www.inah.gob.mx/", file: "gallery/sun-stone.jpg", source: "https://commons.wikimedia.org/wiki/File%3APiedra_del_Sol%2C_Museo_Nacional_de_Antropolog%C3%ADa.jpg", license: "CC BY-SA 4.0", credit: "And chv", note: "The Aztec calendar stone, twenty-four tonnes, and the best known object in Mexico." },
  { name: "Standard of Ur", museum: "British Museum", place: "London", period: "c. 2600 BC", site: "https://www.britishmuseum.org", file: "gallery/standard-of-ur.jpg", source: "https://commons.wikimedia.org/wiki/File%3AStandard_of_Ur_-_War.jpg", license: "Public domain", credit: "Unknown author", note: "A hollow box with inlaid panels: war on one side, the spoils of peace on the other." },
  { name: "Red Fuji", museum: "The Met", place: "New York", period: "c. 1831", site: "https://www.metmuseum.org", file: "gallery/red-fuji.jpg", source: "https://commons.wikimedia.org/wiki/File%3AKatsushika_Hokusai%2C_published_by_Nishimuraya_Yohachi_%28Eijud%C5%8D%29_-_Fine_Wind%2C_Clear_Weather_%28Gaif%C5%AB_kaisei%29%2C_also_known_as_Red_Fuji%2C_from_the_series_Thirty-six_Views_o..._-_Google_Art_Project_-_Cropped.jpg", license: "Public domain", credit: "Katsushika Hokusai", note: "From the same series as the Great Wave, and scarcer: few early impressions survive." },
  { name: "Discobolus", museum: "National Roman Museum", place: "Rome", period: "Roman copy", site: "https://museonazionaleromano.it/", file: "gallery/discobolus.jpg", source: "https://commons.wikimedia.org/wiki/File%3ADiscobolus_in_National_Roman_Museum_Palazzo_Massimo_alle_Terme.JPG", license: "CC BY-SA 4.0", credit: "Livioandronico2013", copy: true, note: "A Roman marble copy of a Greek bronze by Myron; the original has been lost since antiquity." }
];
