window.MUSEUM_SITES = [
  { cat: "technology", name: "GitHub", url: "https://github.com", desc: "The largest host for open source code, built around git, pull requests and issues." },
  { cat: "technology", name: "Stack Overflow", url: "https://stackoverflow.com", desc: "The canonical question and answer archive every working programmer ends up on." },
  { cat: "technology", name: "MDN Web Docs", url: "https://developer.mozilla.org", desc: "The reference of record for HTML, CSS and JavaScript, maintained in the open." },
  { cat: "technology", name: "Google Developers", url: "https://developers.google.com", desc: "Documentation, guides and samples for Google platforms and web tooling." },
  { cat: "technology", name: "Microsoft Learn", url: "https://learn.microsoft.com", desc: "Structured learning paths and reference for Microsoft platforms and languages." },
  { cat: "cloud", name: "AWS", url: "https://aws.amazon.com", desc: "Amazon's cloud: compute, storage and managed services at planetary scale." },
  { cat: "cloud", name: "Azure", url: "https://azure.microsoft.com", desc: "Microsoft's cloud platform, with tight ties to enterprise and hybrid deployments." },
  { cat: "cloud", name: "Google Cloud", url: "https://cloud.google.com", desc: "Google's cloud, strongest where data analytics and machine learning meet." },
  { cat: "technology", name: "Docker", url: "https://www.docker.com", desc: "The container format that made build once, run anywhere a daily habit." },
  { cat: "technology", name: "Kubernetes", url: "https://kubernetes.io", desc: "Container orchestration that became the default control plane for clusters." },
  { cat: "technology", name: "Python", url: "https://www.python.org", desc: "The general purpose language most people reach for first, and often last." },
  { cat: "technology", name: "React", url: "https://reactjs.org", desc: "Component based view library that reshaped how interfaces are composed." },
  { cat: "technology", name: "Vue.js", url: "https://vuejs.org", desc: "A progressive front end framework prized for its gentle learning curve." },
  { cat: "technology", name: "Angular", url: "https://angular.io", desc: "A batteries included framework aimed at large, long lived applications." },
  { cat: "technology", name: "Node.js", url: "https://nodejs.org", desc: "JavaScript on the server, with an event model built for concurrency." },
  { cat: "technology", name: "Rust", url: "https://www.rust-lang.org", desc: "Systems programming with memory safety enforced by the compiler, not discipline." },
  { cat: "technology", name: "Go", url: "https://go.dev", desc: "A small, fast language designed for networked infrastructure and simple deployment." },
  { cat: "technology", name: "TypeScript", url: "https://www.typescriptlang.org", desc: "Static types layered over JavaScript, now the default for large codebases." },
  { cat: "ai", name: "TensorFlow", url: "https://www.tensorflow.org", desc: "Google's machine learning framework, from research prototypes to production graphs." },
  { cat: "ai", name: "PyTorch", url: "https://pytorch.org", desc: "The research community's favourite tensor library, now a production platform too." },
  { cat: "ai", name: "OpenAI", url: "https://openai.com", desc: "The lab behind GPT models and the API ecosystem that grew around them." },
  { cat: "ai", name: "Hugging Face", url: "https://huggingface.co", desc: "The commons of machine learning: models, datasets and tooling, shared openly." },
  { cat: "ai", name: "Kaggle", url: "https://www.kaggle.com", desc: "Competitions, notebooks and public datasets for the data science crowd." },
  { cat: "hardware", name: "NVIDIA Developer", url: "https://developer.nvidia.com", desc: "CUDA, drivers and SDKs for the hardware most AI is trained on." },
  { cat: "technology", name: "Apple Developer", url: "https://developer.apple.com", desc: "Everything needed to ship software on Apple's platforms, including Xcode." },
  { cat: "technology", name: "Android Developers", url: "https://developer.android.com", desc: "Official documentation and tooling for building on Android." },
  { cat: "standards", name: "IETF", url: "https://www.ietf.org", desc: "Where the internet's protocols are argued out and written down as RFCs." },
  { cat: "standards", name: "W3C", url: "https://www.w3.org", desc: "The body standardising the web itself: HTML, CSS, accessibility and beyond." },
  { cat: "academic", name: "IEEE", url: "https://www.ieee.org", desc: "The world's largest technical professional association, heavy on electrical standards." },
  { cat: "academic", name: "ACM", url: "https://www.acm.org", desc: "The computing professional society, publisher of journals and the Turing Award." },
  { cat: "academic", name: "arXiv", url: "https://arxiv.org", desc: "Preprints in physics, maths and computer science, posted before peer review." },
  { cat: "science", name: "Nature", url: "https://www.nature.com", desc: "The weekly journal whose name still signals a result worth noticing." },
  { cat: "science", name: "Science", url: "https://www.science.org", desc: "The AAAS flagship journal, covering every corner of research." },
  { cat: "biology", name: "Cell", url: "https://www.cell.com", desc: "A top tier venue for molecular and cellular biology research." },
  { cat: "medical", name: "The Lancet", url: "https://www.thelancet.com", desc: "One of medicine's oldest journals, known for its global health commissions." },
  { cat: "medical", name: "NEJM", url: "https://www.nejm.org", desc: "The New England Journal of Medicine, clinical evidence since 1812." },
  { cat: "medical", name: "PubMed", url: "https://pubmed.ncbi.nlm.nih.gov", desc: "Free search across tens of millions of biomedical citations and abstracts." },
  { cat: "medical", name: "Cochrane", url: "https://www.cochranelibrary.com", desc: "Systematic reviews separating treatments that work from those that merely persist." },
  { cat: "medical", name: "Mayo Clinic", url: "https://www.mayoclinic.org", desc: "Reference material on diseases and symptoms written for patients, not journals." },
  { cat: "medical", name: "Cleveland Clinic", url: "https://my.clevelandclinic.org", desc: "Health library covering conditions, tests and procedures in plain language." },
  { cat: "education", name: "Harvard University", url: "https://www.harvard.edu", desc: "Oldest university in the United States, and its most cited brand." },
  { cat: "education", name: "MIT", url: "https://www.mit.edu", desc: "Where engineering culture is exported from, courses included." },
  { cat: "education", name: "Stanford University", url: "https://www.stanford.edu", desc: "The university most closely entangled with Silicon Valley." },
  { cat: "education", name: "Oxford University", url: "https://www.ox.ac.uk", desc: "Nine centuries of teaching, still arguing about tutorial supervision." },
  { cat: "education", name: "Cambridge University", url: "https://www.cam.ac.uk", desc: "Home of Newton, Darwin and the Cavendish Laboratory." },
  { cat: "education", name: "Coursera", url: "https://www.coursera.org", desc: "University courses online, many free to audit and paid to certify." },
  { cat: "education", name: "edX", url: "https://www.edx.org", desc: "Open online courses from a consortium of founding universities." },
  { cat: "education", name: "Khan Academy", url: "https://www.khanacademy.org", desc: "Free practice and video lessons from arithmetic to college level maths." },
  { cat: "education", name: "Udacity", url: "https://www.udacity.com", desc: "Career oriented nanodegrees, originally spun out of a Stanford experiment." },
  { cat: "language", name: "Duolingo", url: "https://www.duolingo.com", desc: "Gamified language lessons; the owl is unforgiving if you stop." },
  { cat: "science", name: "National Geographic", url: "https://www.nationalgeographic.com", desc: "Photography and reporting on the natural world since 1888." },
  { cat: "space", name: "NASA", url: "https://www.nasa.gov", desc: "The United States civilian space agency and its archive of everything." },
  { cat: "space", name: "ESA", url: "https://www.esa.int", desc: "Europe's space agency: launchers, Earth observation and deep science." },
  { cat: "physics", name: "CERN", url: "https://home.cern", desc: "The laboratory built around the Large Hadron Collider, where the web was invented." },
  { cat: "space", name: "SpaceX", url: "https://www.spacex.com", desc: "Reusable rockets, and a launch cadence that reset the industry." },
  { cat: "space", name: "Blue Origin", url: "https://www.blueorigin.com", desc: "A slower, steadier approach to reusable launch and lunar cargo." },
  { cat: "environment", name: "NOAA", url: "https://www.noaa.gov", desc: "Weather, oceans and climate data from the US federal government." },
  { cat: "earth", name: "USGS", url: "https://www.usgs.gov", desc: "Geology, earthquakes, water and maps for the United States." },
  { cat: "health", name: "WHO", url: "https://www.who.int", desc: "The United Nations agency that coordinates global public health." },
  { cat: "health", name: "CDC", url: "https://www.cdc.gov", desc: "US public health guidance, surveillance data and outbreak notices." },
  { cat: "health", name: "NIH", url: "https://www.nih.gov", desc: "The largest public funder of biomedical research in the world." },
  { cat: "international", name: "UN", url: "https://www.un.org", desc: "The post war assembly of nearly every recognised state." },
  { cat: "finance", name: "World Bank", url: "https://www.worldbank.org", desc: "Development lending, plus open indicators on every economy you can name." },
  { cat: "finance", name: "IMF", url: "https://www.imf.org", desc: "Lender of last resort to states, and publisher of global outlooks." },
  { cat: "trade", name: "WTO", url: "https://www.wto.org", desc: "The rules and dispute machinery behind most international trade." },
  { cat: "economics", name: "OECD", url: "https://www.oecd.org", desc: "Comparable statistics across rich economies, and the policy papers built on them." },
  { cat: "finance", name: "Bloomberg", url: "https://www.bloomberg.com", desc: "Markets reporting plus the terminal that defined financial data." },
  { cat: "news", name: "Reuters", url: "https://www.reuters.com", desc: "Wire service reporting, founded on carrier pigeons and submarine cables." },
  { cat: "finance", name: "Financial Times", url: "https://www.ft.com", desc: "Salmon coloured business paper with unusual reach into policy circles." },
  { cat: "finance", name: "Wall Street Journal", url: "https://www.wsj.com", desc: "US business daily with a respected newsroom behind the paywall." },
  { cat: "business", name: "Forbes", url: "https://www.forbes.com", desc: "Business journalism best known for its lists of wealth and influence." },
  { cat: "management", name: "Harvard Business Review", url: "https://hbr.org", desc: "Essays on strategy and leadership that set consulting vocabulary." },
  { cat: "consulting", name: "McKinsey", url: "https://www.mckinsey.com", desc: "The first name in management consulting, with a research arm attached." },
  { cat: "consulting", name: "BCG", url: "https://www.bcg.com", desc: "Strategy consulting house known for the growth share matrix." },
  { cat: "consulting", name: "Bain", url: "https://www.bain.com", desc: "Consulting firm closely associated with private equity diligence." },
  { cat: "accounting", name: "Deloitte", url: "https://www.deloitte.com", desc: "Largest professional services network by revenue, audit to advisory." },
  { cat: "accounting", name: "PwC", url: "https://www.pwc.com", desc: "Audit and advisory network present in nearly every major market." },
  { cat: "accounting", name: "EY", url: "https://www.ey.com", desc: "Assurance, tax and transaction advisory across 150 countries." },
  { cat: "accounting", name: "KPMG", url: "https://kpmg.com", desc: "Audit, tax and advisory with deep roots in financial services." },
  { cat: "markets", name: "Nasdaq", url: "https://www.nasdaq.com", desc: "The electronic exchange that made screen trading the norm." },
  { cat: "markets", name: "NYSE", url: "https://www.nyse.com", desc: "The New York Stock Exchange; listing here still means something." },
  { cat: "markets", name: "CME Group", url: "https://www.cmegroup.com", desc: "The derivatives marketplace behind most futures volume." },
  { cat: "crypto", name: "CoinDesk", url: "https://www.coindesk.com", desc: "Reporting and price indices for digital assets, since 2013." },
  { cat: "crypto", name: "Coinbase", url: "https://www.coinbase.com", desc: "A publicly listed exchange aimed at newcomers and institutions alike." },
  { cat: "crypto", name: "Binance", url: "https://www.binance.com", desc: "The largest cryptocurrency exchange by volume, and the most scrutinised." },
  { cat: "design", name: "Behance", url: "https://www.behance.net", desc: "Portfolio platform where designers post full project case studies." },
  { cat: "design", name: "Dribbble", url: "https://dribbble.com", desc: "Small shots, big influence on interface trends and visual style." },
  { cat: "webdesign", name: "Awwwards", url: "https://www.awwwards.com", desc: "The jury for visually ambitious websites, with plenty of debate attached." },
  { cat: "design", name: "Pinterest", url: "https://www.pinterest.com", desc: "A searchable board of images that quietly became a discovery engine." },
  { cat: "design", name: "Figma", url: "https://www.figma.com", desc: "Design in the browser, multiplayer, with handoff built in." },
  { cat: "design", name: "Adobe", url: "https://www.adobe.com", desc: "Photoshop, Illustrator and the Creative Cloud subscription that followed." },
  { cat: "design", name: "Canva", url: "https://www.canva.com", desc: "Templates that let anyone produce passable graphics in minutes." },
  { cat: "design", name: "Sketch", url: "https://www.sketch.com", desc: "The Mac design tool that defined the vector interface era before Figma." },
  { cat: "design", name: "InVision", url: "https://www.invisionapp.com", desc: "Prototyping and handoff tooling from design's collaboration boom." },
  { cat: "design", name: "Muzli", url: "https://muz.li", desc: "A daily feed of interface and visual inspiration, collected automatically." },
  { cat: "architecture", name: "Dezeen", url: "https://www.dezeen.com", desc: "The architecture and design magazine most of the industry reads." },
  { cat: "architecture", name: "ArchDaily", url: "https://www.archdaily.com", desc: "Project archive and news for architects, huge and genuinely browsable." },
  { cat: "architecture", name: "Domus", url: "https://www.domusweb.it", desc: "Italian design review running since 1928, still opinionated." },
  { cat: "design", name: "Designboom", url: "https://www.designboom.com", desc: "Daily design, architecture and art coverage from Milan." },
  { cat: "art", name: "ArtStation", url: "https://www.artstation.com", desc: "Where concept artists and game illustrators keep their best work." },
  { cat: "art", name: "DeviantArt", url: "https://www.deviantart.com", desc: "An older, enormous artist community that predates every modern feed." },
  { cat: "art", name: "Saatchi Art", url: "https://www.saatchiart.com", desc: "A marketplace for original art, mostly from emerging artists." },
  { cat: "art", name: "Artsy", url: "https://www.artsy.net", desc: "Gallery inventory and art market data in one searchable place." },
  { cat: "art", name: "Google Arts & Culture", url: "https://artsandculture.google.com", desc: "High resolution works and virtual galleries from partner institutions." },
  { cat: "museum", name: "The Met", url: "https://www.metmuseum.org", desc: "Five thousand years of art in one building, much of it online." },
  { cat: "museum", name: "Louvre", url: "https://www.louvre.fr", desc: "The most visited museum in the world, glass pyramid included." },
  { cat: "museum", name: "British Museum", url: "https://www.britishmuseum.org", desc: "Eight million objects, collected across an empire and endlessly contested." },
  { cat: "museum", name: "MoMA", url: "https://www.moma.org", desc: "The museum that decided what modern art meant for most of a century." },
  { cat: "museum", name: "Tate", url: "https://www.tate.org.uk", desc: "Britain's national collection plus Turbine Hall commissions." },
  { cat: "museum", name: "Smithsonian", url: "https://www.si.edu", desc: "Nineteen museums and a zoo, most of it free to visit." },
  { cat: "library", name: "Library of Congress", url: "https://www.loc.gov", desc: "The largest library in the world, with a vast digitised archive." },
  { cat: "culture", name: "Europeana", url: "https://www.europeana.eu", desc: "A single search over thousands of European heritage collections." },
  { cat: "library", name: "Internet Archive", url: "https://archive.org", desc: "Books, recordings, software and the Wayback Machine itself." },
  { cat: "reference", name: "Wikipedia", url: "https://www.wikipedia.org", desc: "The collaborative encyclopaedia that replaced every printed set." },
  { cat: "reference", name: "Wikidata", url: "https://www.wikidata.org", desc: "Structured knowledge behind the facts, machine readable and freely reused." },
  { cat: "media", name: "TED", url: "https://www.ted.com", desc: "Short talks with long reach, subtitled into dozens of languages." },
  { cat: "media", name: "PBS", url: "https://www.pbs.org", desc: "American public broadcasting: documentaries, news hours and science series." },
  { cat: "news", name: "BBC", url: "https://www.bbc.com", desc: "UK public broadcaster with one of the widest news operations anywhere." },
  { cat: "news", name: "CNN", url: "https://www.cnn.com", desc: "The network that invented 24 hour television news in 1980." },
  { cat: "news", name: "The New York Times", url: "https://www.nytimes.com", desc: "American newspaper of record, now mostly a subscription bundle." },
  { cat: "news", name: "The Guardian", url: "https://www.theguardian.com", desc: "UK liberal daily funded by readers rather than a proprietor." },
  { cat: "news", name: "Al Jazeera", url: "https://www.aljazeera.com", desc: "Doha based channel that changed the map of international news." },
  { cat: "news", name: "NPR", url: "https://www.npr.org", desc: "US public radio; the reporting behind most American commutes." },
  { cat: "news", name: "AP News", url: "https://apnews.com", desc: "A cooperative wire service whose copy every outlet republishes." },
  { cat: "technology", name: "Hacker News", url: "https://news.ycombinator.com", desc: "The town square for programmers, arguing since 2007." },
  { cat: "startup", name: "Product Hunt", url: "https://www.producthunt.com", desc: "Daily leaderboard of launches, and the audience that greets them." },
  { cat: "startup", name: "TechCrunch", url: "https://techcrunch.com", desc: "Startup coverage that doubled as the industry's press release channel." },
  { cat: "technology", name: "The Verge", url: "https://www.theverge.com", desc: "Reporting on how technology reshapes culture, and vice versa." },
  { cat: "technology", name: "Wired", url: "https://www.wired.com", desc: "The magazine that turned cyberculture into a news beat." },
  { cat: "technology", name: "Ars Technica", url: "https://arstechnica.com", desc: "Deep technical reporting written for people who have read the source." },
  { cat: "technology", name: "MIT Technology Review", url: "https://www.technologyreview.com", desc: "MIT's independent magazine covering emerging technology and its consequences." },
  { cat: "engineering", name: "IEEE Spectrum", url: "https://spectrum.ieee.org", desc: "Engineering magazine covering robotics, energy and everything in between." },
  { cat: "community", name: "Quora", url: "https://www.quora.com", desc: "Questions answered by whoever turns up, with varying results." },
  { cat: "community", name: "Reddit", url: "https://www.reddit.com", desc: "The front page, assembled from a hundred thousand subreddits." },
  { cat: "community", name: "Medium", url: "https://medium.com", desc: "Publishing platform where essays go, and sometimes get read." },
  { cat: "community", name: "Substack", url: "https://substack.com", desc: "Newsletters paid for directly, and the writers who moved for them." },
  { cat: "community", name: "Discord", url: "https://discord.com", desc: "Chat built for gamers, adopted by every community since." },
  { cat: "business", name: "Slack", url: "https://slack.com", desc: "Team chat that replaced internal email across an entire industry." },
  { cat: "productivity", name: "Notion", url: "https://www.notion.so", desc: "Documents, databases and wikis collapsed into one flexible workspace." },
  { cat: "productivity", name: "Trello", url: "https://trello.com", desc: "Kanban boards simple enough for anyone to grasp in a minute." },
  { cat: "productivity", name: "Asana", url: "https://asana.com", desc: "Work tracking for teams who need more structure than a checklist." },
  { cat: "business", name: "Zoom", url: "https://zoom.us", desc: "Video calls that became the default interface for remote work." },
  { cat: "business", name: "Salesforce", url: "https://www.salesforce.com", desc: "The CRM that made software a subscription and then a platform." },
  { cat: "enterprise", name: "SAP", url: "https://www.sap.com", desc: "Enterprise resource planning running the back office of huge companies." },
  { cat: "enterprise", name: "Oracle", url: "https://www.oracle.com", desc: "Databases, enterprise applications and a famously aggressive sales culture." },
  { cat: "enterprise", name: "IBM", url: "https://www.ibm.com", desc: "A century old computing company now betting on hybrid cloud and quantum." },
  { cat: "consulting", name: "Accenture", url: "https://www.accenture.com", desc: "Consulting at industrial scale, with implementation to follow." },
  { cat: "ecommerce", name: "Shopify", url: "https://www.shopify.com", desc: "Everything needed to run a shop online, own brand not included." },
  { cat: "ecommerce", name: "Amazon", url: "https://www.amazon.com", desc: "A bookstore that became a marketplace, then a computing platform." },
  { cat: "ecommerce", name: "eBay", url: "https://www.ebay.com", desc: "The auction site where almost anything is still for sale." },
  { cat: "ecommerce", name: "Alibaba", url: "https://www.alibaba.com", desc: "Wholesale trade platform behind a large share of Chinese exports." },
  { cat: "travel", name: "Booking.com", url: "https://www.booking.com", desc: "Hotel booking at enormous scale, with reviews nobody can fake easily." },
  { cat: "travel", name: "Airbnb", url: "https://www.airbnb.com", desc: "Rooms in other people's homes, and the cities that argue about them." },
  { cat: "transport", name: "Uber", url: "https://www.uber.com", desc: "Ride hailing that rewrote labour law wherever it landed." },
  { cat: "business", name: "LinkedIn", url: "https://www.linkedin.com", desc: "Professional networking that everyone maintains and nobody enjoys." }
];
